printWidth: 100
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
useTabs: false
plugins: 
  - './node_modules/prettier-plugin-astro'
overrides: 
  - files: 'CHANGELOG.md'
    options:
      plugins: []
  - files: '**/*.astro'
    options: 
      parser: 'astro'
